In [1]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [2]:
glass_df = pd.read_csv("glass.csv")
glass_df.head(10)


RI     Na    Mg    Al     Si     K    Ca   Ba    Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.00     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.00     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.00     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.00     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.00     1
5  1.51596  12.79  3.61  1.62  72.97  0.64  8.07  0.0  0.26     1
6  1.51743  13.30  3.60  1.14  73.09  0.58  8.17  0.0  0.00     1
7  1.51756  13.15  3.61  1.05  73.24  0.57  8.24  0.0  0.00     1
8  1.51918  14.04  3.58  1.37  72.08  0.56  8.30  0.0  0.00     1
9  1.51755  13.00  3.60  1.36  72.99  0.57  8.40  0.0  0.11     1

In [3]:
from sklearn.utils import shuffle
df = shuffle(glass_df,random_state=33)
df.head()

RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
205  1.51732  14.95  0.00  1.80  72.99  0.00  8.61  1.55  0.0     7
82   1.51646  13.41  3.55  1.25  72.81  0.68  8.10  0.00  0.0     2
81   1.51593  13.25  3.45  1.43  73.17  0.61  7.86  0.00  0.0     2
17   1.52196  14.36  3.85  0.89  71.36  0.15  9.15  0.00  0.0     1
8    1.51918  14.04  3.58  1.37  72.08  0.56  8.30  0.00  0.0     1

In [4]:
type_labels = pd.unique(df.Type)
type_labels

array([7, 2, 1, 5, 3, 6])

In [5]:
X = df.drop(['Type'], axis = 1)
X
"""a =max 
b= min 

min_df = df-b/a-b"""

'a =max \nb= min \n\nmin_df = df-b/a-b'

In [6]:
y = df["Type"]
y

205    7
82     2
81     2
17     1
8      1
      ..
201    7
146    3
66     1
135    2
20     1
Name: Type, Length: 214, dtype: int64

In [7]:
X.describe().T

count       mean       std       min        25%       50%        75%  \
RI  214.0   1.518365  0.003037   1.51115   1.516522   1.51768   1.519157   
Na  214.0  13.407850  0.816604  10.73000  12.907500  13.30000  13.825000   
Mg  214.0   2.684533  1.442408   0.00000   2.115000   3.48000   3.600000   
Al  214.0   1.444907  0.499270   0.29000   1.190000   1.36000   1.630000   
Si  214.0  72.650935  0.774546  69.81000  72.280000  72.79000  73.087500   
K   214.0   0.497056  0.652192   0.00000   0.122500   0.55500   0.610000   
Ca  214.0   8.956963  1.423153   5.43000   8.240000   8.60000   9.172500   
Ba  214.0   0.175047  0.497219   0.00000   0.000000   0.00000   0.000000   
Fe  214.0   0.057009  0.097439   0.00000   0.000000   0.00000   0.100000   

         max  
RI   1.53393  
Na  17.38000  
Mg   4.49000  
Al   3.50000  
Si  75.41000  
K    6.21000  
Ca  16.19000  
Ba   3.15000  
Fe   0.51000

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)


In [9]:
y_train.value_counts()

2    61
1    56
7    23
3    14
5    10
6     7
Name: Type, dtype: int64

In [10]:
print(len(X))       #-->171+43 = 214
print(len(y))       #-->171+43 = 214
print(len(X_train)) #-->171
print(len(X_test))  #--> 43
print(len(y_train)) #-->171
print(len(y_test))  #--> 43

214
214
171
43
171
43


In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
# Fit only on X_train
scaler.fit(X_train)

# Scale both X_train and X_test
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

array([[-1.08025504,  2.16762885, -1.85173384, ..., -0.44610235,
         0.94431682, -0.59938887],
       [ 1.25231975, -0.22821707,  0.74536668, ...,  0.74704804,
        -0.36277879, -0.59938887],
       [ 0.41389776,  1.69833944,  0.73158896, ...,  0.0226353 ,
        -0.36277879, -0.59938887],
       ...,
       [ 0.30950281,  0.30282094,  0.58692288, ..., -0.05548764,
        -0.05156555,  1.85559308],
       [ 1.21317164,  0.98205561,  0.75225554, ...,  0.1220645 ,
        -0.36277879,  3.18537496],
       [ 0.21489488,  0.74741091, -0.20529611, ...,  0.42745419,
        -0.36277879, -0.59938887]])

In [12]:
col_names= X.columns 
scaled_df = pd.DataFrame(X_train, columns=col_names)
scaled_df.describe().T

count          mean       std       min       25%       50%       75%  \
RI  171.0  1.059127e-14  1.002937 -2.362356 -0.608847 -0.228784  0.296453   
Na  171.0 -1.350447e-15  1.002937 -3.290948 -0.592534 -0.178818  0.481892   
Mg  171.0  2.493132e-16  1.002937 -1.851734 -0.360295  0.545590  0.635145   
Al  171.0 -1.558208e-17  1.002937 -2.221596 -0.508459 -0.161982  0.357734   
Si  171.0  6.840532e-15  1.002937 -3.802932 -0.454698  0.183060  0.541800   
K   171.0  5.843279e-17  1.002937 -0.842991 -0.630012  0.133164  0.239654   
Ca  171.0 -1.375118e-15  1.002937 -2.512809 -0.495817 -0.261448  0.168228   
Ba  171.0  7.271636e-17  1.002937 -0.362779 -0.362779 -0.362779 -0.362779   
Fe  171.0 -4.155221e-17  1.002937 -0.599389 -0.599389 -0.599389  0.423520   

          max  
RI   5.069260  
Na   4.921617  
Mg   1.241365  
Al   3.957246  
Si   3.637587  
K   10.178690  
Ca   5.129035  
Ba   6.172699  
Fe   4.617448

In [13]:
#import GridSearchCV
from sklearn.model_selection import GridSearchCV

#In case of classifier like knn the parameter to be tuned is n_neighbors
param_grid = {'n_neighbors':np.arange(1,20)}

knn3 = KNeighborsClassifier()
knn_cv= GridSearchCV(knn3,param_grid,cv=5)
knn_cv.fit(X_test,y_test)

print("Best Score:" + str(knn_cv.best_score_))
print("Best Parameters: " + str(knn_cv.best_params_))

Best Score:0.5611111111111111
Best Parameters: {'n_neighbors': 1}


/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(


In [14]:
from sklearn.neighbors import KNeighborsClassifier
regressor = KNeighborsClassifier(n_neighbors= 5) #knn_cv.best_params_
regressor.fit(X_train, y_train)

KNeighborsClassifier()

In [15]:
y_pred = regressor.predict(X_test)
y_pred

array([7, 2, 2, 7, 1, 1, 5, 2, 2, 2, 1, 1, 7, 6, 1, 7, 7, 2, 1, 5, 1, 2,
       2, 2, 2, 1, 2, 1, 1, 1, 7, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 2])

In [16]:
np.array(y_test)

array([7, 5, 2, 5, 1, 1, 2, 2, 1, 1, 3, 1, 7, 6, 2, 7, 7, 1, 1, 5, 1, 1,
       7, 2, 2, 3, 2, 2, 2, 2, 7, 3, 1, 2, 2, 2, 1, 1, 2, 1, 1, 2, 6])

In [17]:
count=0
for i in range(len(y_test)):
    if y_pred[i] != np.array(y_test)[i]:
        count +=1
print(count)  # 43 tahminden 13 tahmin eşleşmiyor. 

19


In [18]:
from sklearn.metrics import classification_report

target_names = ["1","3", "5", "2", "6", "7"]

print(classification_report(y_test, y_pred, target_names=target_names))


              precision    recall  f1-score   support

           1       0.50      0.64      0.56        14
           3       0.50      0.53      0.52        15
           5       0.00      0.00      0.00         3
           2       0.50      0.33      0.40         3
           6       1.00      0.50      0.67         2
           7       0.83      0.83      0.83         6

    accuracy                           0.56        43
   macro avg       0.56      0.47      0.50        43
weighted avg       0.53      0.56      0.54        43



/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

In [19]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)


array([[9, 5, 0, 0, 0, 0],
       [6, 8, 0, 1, 0, 0],
       [3, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1],
       [0, 1, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 5]])